# Generated by Django 5.0.4 on 2024-08-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.IntegerField()),
                ('estado', models.BooleanField()),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('num_telefono', models.IntegerField()),
                ('fecha_ingreso', models.DateField(null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('torre_servicio', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=100)),
                ('convenio', models.CharField(choices=[('PP', 'Petroleros Privados'), ('PJ', 'Petroleros Jerarquicos')], max_length=2)),
            ],
        ),
    ]
