# Generated by Django 5.0.4 on 2024-08-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='estado',
            field=models.CharField(choices=[('ACT', 'ACTIVO'), ('IN', 'INACTIVO')], max_length=15),
        ),
    ]
