# Generated by Django 5.0.4 on 2024-08-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colaboradores', '0002_alter_empleado_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='zona',
            field=models.CharField(choices=[('CS', 'CAÑADON SECO'), ('LH', 'LAS HERAS'), ('CH', 'CHUBUT'), ('TDF', 'TIERRA DEL FUEGO'), ('REGIONAL', 'REGIONAL')], max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='torre_servicio',
            field=models.CharField(choices=[('COM', 'COMUNICACIONES'), ('INFRA', 'INFRAESTRUCTURA'), ('SOP', 'SERVICIOS DIGITALES'), ('OD', 'ON DEMAND'), ('GDA', 'GESTION DE ACTIVOS')], max_length=220),
        ),
    ]
