# Generated by Django 5.0.4 on 2024-08-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colaboradores', '0003_empleado_zona_alter_empleado_torre_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='dni',
            field=models.IntegerField(default=0),
        ),
    ]
