# Generated by Django 5.0.4 on 2024-08-11 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Colaboradores', '0004_empleado_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venc_examen_periodico', models.DateField()),
                ('venc_lic_conducir', models.DateField()),
                ('venc_man_defensivo', models.DateField()),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Colaboradores.empleado')),
            ],
        ),
    ]
