# Generated by Django 5.0.4 on 2024-08-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Habilitada', 'Habilitada'), ('Inhabilitada', 'Inhabilitada')], max_length=220)),
                ('alarma', models.IntegerField()),
                ('wifi', models.CharField(max_length=100)),
            ],
        ),
    ]
